apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
        - image: registry.alexbissessur.dev:5000/whereami:latest
          name: nginx
          ports:
            - containerPort: 80
          resources:
	    limits:
	      cpu: 500m
	    requests:
    	      cpu: 200m
